Add NodeJS v7 to package.json
strongloop/loopback-context pull request #31
Opened 2017-06-20 09:42 UTC by xnf

### Description
Added NodeJS v7 to package.json. 
This way yarn will not complain when node 7 is used.
Tests still pass and the package itself also works on Node 7.

#### Related issues

Fixes #29 Add support for Node 7

### Checklist
- [ ] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

2017-06-20 09:42 UTC, slnode commented
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

2017-06-20 09:42 UTC, slnode commented
Can one of the admins verify this patch?

2017-06-20 09:42 UTC, slnode commented
Can one of the admins verify this patch?

2017-06-21 15:22 UTC, bajtos requested changes
Hi @xnf, thank you for the pull request. Is there any particular reason why you are sticking to Node.js 7, when Node.js 8 has been already released? Would you mind including the version 8 in the list of supported versions too?

More importantly, please modify `.travis.yml` file to run CI tests on the newly added platforms, in order to verify that the module correctly works on them.

2017-07-10 11:20 UTC, xnf commented
Omg, this collaboration flow is soo bad from my side. Sorry for that. 

Thing is that i have a server with v7 and just want to use loopback-context. Test for V8 failed. and as for me - i don't even need it.

2017-07-10 13:53 UTC, bajtos commented
No worries! Let's add just Node.js 7 then. I have squashed your commits into a single one and improved the commit message a bit. Let's wait for CI results before landing.

2017-07-10 13:55 UTC, bajtos approved these changes

2017-07-10 13:56 UTC, merged

2017-07-10 13:56 UTC, bajtos commented
Landed, thank you for the contribution 🎉