Update package.json, setting node version
strongloop/loopback-context pull request #54
Opened 2020-02-10 18:01 UTC by ahmetcetin

setting node version the same as in loopback-datasource-juggler to support new versions of node.

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-context) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [ ] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

2020-02-10 18:01 UTC, slnode commented
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

2020-02-11 08:50 UTC, bajtos requested changes
Thank you for the pull request. I am fine to expand the range of supported Node.js versions, but we need to change the way how it's done, see my comment below.

2020-02-11 08:50 UTC, bajtos commented on package.json
> +    "node": ">=8"
@ahmetcetin please note that we are intentionally limiting the Node.js versions supported by this module. The implementation depends on Node.js functionality that used to change between major versions of Node, we need to test the module against each new major version before we can claim it as being supported.

I am proposing the following version spec:

```suggestion
    "node": "^8.2.1 || ^10.14 || ^12.15"
```

2020-02-11 08:50 UTC, bajtos commented
@slnode ok to test

2020-02-11 08:51 UTC, bajtos commented
@ahmetcetin one more thing: please update Travis CI configuration to run the tests on Node.js 12 version, so that we can verify that loopback-context actually does support it.

See here:

https://github.com/strongloop/loopback-context/blob/a575d934a7c0a9895e4c9baa714da792b487f4f2/.travis.yml#L3-L5

2020-02-11 10:11 UTC, ahmetcetin commented
All requested changes done.

2020-02-17 06:53 UTC, nabdelgadir commented
Thanks @ahmetcetin for this PR! Before we can land it, can you squash your commits into one commit (see [here](https://loopback.io/doc/en/lb4/submitting_a_pr.html#10-final-rebase-and-squashing-of-commits) if you need help)? Also, make sure to use new lines in your commit message so no lines exceed 72 characters. Here's a suggestion:

```
chore: add support for Node.js 12

> Setting the Node.js version to be the same as in 
> loopback-datasource-juggler to support new versions of Node.js
```

2020-02-17 10:41 UTC, bajtos commented
IMO, adding support for a new Node.js version is not a `chore`, it's a `feat`ure. 

Having said that, we are not following conventional commit conventions in this repository, I think the following would be the best commit summary:

```
Add support for Node.js 12
```

2020-02-17 10:42 UTC, bajtos approved these changes

2020-02-17 10:47 UTC, merged

2020-02-17 10:47 UTC, bajtos commented
Landed, thank you @ahmetcetin for the contribution!